# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Dropbox\hobby\Modding\Projects\Project_creator\conf_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
import configparser

from PyQt5.QtWidgets import QDialog, QFileDialog, QMessageBox, QTreeWidgetItem
import gid_pack.gid_ssentials as gis
import gid_pack.gid_qt as giq

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(479, 166)
        Dialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(390, 10, 81, 621))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(25, 25, 356, 134))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.normal_output_lineedit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.normal_output_lineedit.setObjectName("normal_output_lineedit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.normal_output_lineedit)
        self.repo_output_lineedit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.repo_output_lineedit.setObjectName("repo_output_lineedit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.repo_output_lineedit)
        self.normal_push_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.normal_push_button.setObjectName("normal_push_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.normal_push_button)
        self.repo_push_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.repo_push_button.setObjectName("repo_push_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.repo_push_button)
        self.verticalLayout.addLayout(self.formLayout)
        self.cfg_loc = gis.pathmaker('cwd', 'config', 'user_config.ini')

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(lambda: self.write_into_user_config(Dialog.accept))
        self.buttonBox.rejected.connect(Dialog.reject)
        self.normal_push_button.pressed.connect(self.get_normal_path)
        self.repo_push_button.pressed.connect(self.get_repo_path)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def get_normal_path(self):
        giq.as_filedialog(in_type='directory', in_title='Open folder', in_dir=None, in_filter_name=None, in_ext=None, in_output_object=self.normal_output_lineedit.setText)

    def get_repo_path(self):
        giq.as_filedialog(in_type='directory', in_title='Open folder', in_dir=None, in_filter_name=None, in_ext=None, in_output_object=self.repo_output_lineedit.setText)

    def write_into_user_config(self, accept_thing):
        cfg = configparser.ConfigParser()
        cfg.read(self.cfg_loc)
        if self.normal_output_lineedit.text() != '':
            cfg.set('from_user', 'output_location', self.normal_output_lineedit.text())
        if self.repo_output_lineedit.text() != '':
            cfg.set('from_user', 'repo_output_location', self.repo_output_lineedit.text())
        with open(self.cfg_loc, 'w') as new_c:
            cfg.write(new_c)
        accept_thing()


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Configuration"))
        self.normal_push_button.setText(_translate("Dialog", "Normal Output"))
        self.repo_push_button.setText(_translate("Dialog", "Repo Output"))








